print("Введите первое число:")
a=int(input())
print("Введите второе число:")
b=int(input())
print("Введите третье число:")
c=int(input())
print("Сумма введенных чисел: ",a+b+c)
print("Произведение введенных чисел: ",a*b*c)
print("type 'end' to exit ")
e=str(input())
